services:
  postgres:
    image: postgres:16-alpine
    container_name: wayblog-postgres
    ports:
      - '6432:5432'
    environment:
      POSTGRES_DB: wayblog
      POSTGRES_USER: wayblog
      POSTGRES_PASSWORD: wayblog_dev_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: wayblog-redis
    ports:
      - '6381:6379'
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
